language: node_js
sudo: false
node_js:
  - "4"
  - "6"
  - "node"
script: "npm run-script test-travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
